### ISSUE TITLE
get_score超时导致程序停止，建议在web_wait方法下添加异常捕获

### ISSUE THREAD

**Issue by ChaojuWang** [Kevin-lou/xuexi#7]
尝试修改如下：
![image](https://user-images.githubusercontent.com/14054604/69685689-6a137e00-1111-11ea-807e-f2a0afc14456.png)
没有测试==因为修改过后没有遇到超时问题

**Comment by Kevin-lou** [comment]
> 尝试修改如下：
> ![image](https://user-images.githubusercontent.com/14054604/69685689-6a137e00-1111-11ea-807e-f2a0afc14456.png)
> 没有测试==因为修改过后没有遇到超时问题

有道理！

**Comment by ChaojuWang** [comment]
还有print到本行开头的时候在最后补空格可以解决重影问题
![image](https://user-images.githubusercontent.com/14054604/69740930-48a4a780-118e-11ea-8582-c19263637ea2.png)
![image](https://user-images.githubusercontent.com/14054604/69741047-7ee22700-118e-11ea-81f7-a0e5dd294ed3.png)

**Comment by Kevin-lou** [comment]
> 还有print到本行开头的时候在最后补空格可以解决重影问题
> ![image](https://user-images.githubusercontent.com/14054604/69740930-48a4a780-118e-11ea-8582-c19263637ea2.png)
> ![image](https://user-images.githubusercontent.com/14054604/69741047-7ee22700-118e-11ea-81f7-a0e5dd294ed3.png)

修改了，谢谢！
